### ISSUE TITLE
Sticky Layer can't be imported and is missing in node_modules

### ISSUE THREAD

**Issue by Nico-Mayer** [kindoflew/svelte-parallax#31]
Hey, I am on Version 0.5.2 and I am unable to import the StickyLayer component so I looked up the node_modules and there the StickyLayer.svelte component is also missing, I tried to reinstall svelte-parallax, but this also did not fix it.

**Comment by kindoflew** [comment]
hi! 

its my fault for not making it clearer -- but the version with `StickyLayer` has not been released yet. 

i'm away from my computer until tuesday, but i'll publish a new version then!

**Comment by kindoflew** [comment]
@Nico-Mayer `StickyLayer` is now available with version `0.6.0`.
